### ISSUE TITLE
[bug] - Max floor temperature not reached even if room temperature is below setpoint

### ISSUE THREAD

**Issue by Eiritj** [swingerman/ha-dual-smart-thermostat#297] opened 2024-09-25 18:27 UTC
Hello.
I'm having an issue where the thermostat never reaches the setpoint.

Configuration:
![image](https://github.com/user-attachments/assets/22fe91e7-794d-4f91-9d9c-65d6e33951bb)

Current temperature 24°C, setpoint 25°C:
![image](https://github.com/user-attachments/assets/0d4c2ab6-ad2e-4b8e-8b4f-3bd214412bc9)

Floor temperature:
![image](https://github.com/user-attachments/assets/b61ac461-09ee-41b8-9e85-80af96b63e65)

Heater behaviour:
![image](https://github.com/user-attachments/assets/541de489-23a3-44b6-bacd-32cfc33db298)

Did I do something wrong in the config?

Also, it seems the full configuration example is missing some things, like the sensor_stale_duration.

**Comment by swingerman** [comment] 2024-09-26 10:35
Thanks for reporting this. I will look into this.

**Comment by Kentrp** [comment] 2024-09-26 13:39
Hi! The same thing

**Comment by Eiritj** [comment] 2024-09-27 19:35
I'm very much a n00b so please consider that this could be caused by user error.
Just in case it is helpful, I'll ad a picture showing more of my config. Let me know if there is something else I can provide that could be useful.
![Screenshot_20240927-213351](https://github.com/user-attachments/assets/5174a122-2f43-4f21-a2cb-91945e5329d5)

**Comment by michalg91** [comment] 2024-10-04 09:22
Same situation in my setup.

**Comment by swingerman** [comment] 2024-10-17 09:28
@Eiritj  From the thermostat's history, I can see that it reached 24 degrees. 24 is your target, and it reached it and the thermostat turned off the heater.
The max_floor_temp is a safety setting that shuts off the heating to protect your floor structure from overheating. I did not mean to heat the floor up to the max.
Let me know if I understand your situation correctly.

**Comment by swingerman** [comment] 2024-10-17 09:29
Closing for now as it seems to be working as intended

**Comment by Eiritj** [comment] 2024-10-17 09:42
Hi. No, 25 is the target:

![17291581057737454610988409540308](https://github.com/user-attachments/assets/d4993d2f-7394-4ef1-82fb-5d54366ccde7)

The heater is on only very brief periods of time, and seems to be limited by 28°C on the floor sensors even if I set the limit in the config to 30°C.

**Comment by swingerman** [comment] 2024-10-17 10:36
Could you check the `hvac_action_reason` state attribute while it's not heating? It should show why it's in that state.

**Comment by swingerman** [comment] 2024-10-17 14:34
As workaround, you can try to remove the min_cycle_duration from your config as it seems the logic that it brings in has a bug.

**Comment by Eiritj** [comment] 2024-10-17 14:51
> Could you check the `hvac_action_reason` state attribute while it's not heating? It should show why it's in that state.

Yes, but I am not sure how to do that. Do I need to make an automation for every value?

> As workaround, you can try to remove the min_cycle_duration from your config as it seems the logic that it brings in has a bug.

I'll remove it for one of the heaters and keep it for the rest so we can see the difference. Thanks a lot for the suggestion.

**Comment by swingerman** [comment] 2024-10-18 09:03
Never mind. I figured it.
The fix will be in the next release

**Closed** 2024-10-18 09:03 UTC
Labels: bug
