### ISSUE TITLE
Feature request: fan mode

### ISSUE THREAD

**Issue by lb-sgent** [swingerman/ha-dual-smart-thermostat#27] opened 2022-07-04 13:53 UTC
It is possible to add fan hvac mode? It will be nice to have if someone have air condition with fan option.

**Comment by swingerman** [comment] 2022-12-08 09:13
I only can think about setting fan mode in the config at this point. This means the thermostat will only work on fan mode until the config changes. Would this be OK for you?

**Comment by swingerman** [comment] 2023-12-20 11:03
duplicate of #47

**Closed by swingerman** 2023-12-20 11:03 UTC
