### ISSUE TITLE
preset mode being set on wrong entity

### ISSUE THREAD

**Issue by mbrevda** [swingerman/ha-dual-smart-thermostat#80] opened 2023-10-17 06:47 UTC
Hi - got a strange issue here. Looks like my preset modes are being set on the wrong entity.  Notice how the "Dining Room" has two preset modes - and the boys room has none. I'm seeing this in other entities, too.
<img width="1014" alt="Screenshot 2023-10-17 at 9 44 37 AM" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/293004/40bfa655-4126-4d2e-8394-6757214bc07e">

Here is the configuration for these two:

```yaml
- platform: dual_smart_thermostat
  name: Boys Room
  heater: switch.boys_room_radiator
  cooler: switch.boys_room_air_conditioner
  target_sensor: sensor.boys_room_temperature_temperature
  min_cycle_duration: 60
  precision: .5
  min_temp: 20
  max_temp: 25
  heat_cool_mode: true
  away:
    temperature: 30
    target_temp_low: 50
    target_temp_high: 0

- platform: dual_smart_thermostat
  name: Dining Room
  heater: switch.dining_room_radiator
  target_sensor: sensor.dining_room_thermostat_temperature
  min_cycle_duration: 60
  precision: .5
  min_temp: 20
  max_temp: 25
  away:
    temperature: 15

```

Is this something on my end? Thanks!

**Comment by mbrevda** [comment] 2023-11-02 09:36
bump - anything I can do to move this forward?

**Comment by swingerman** [comment] 2024-03-08 13:44
- `preset_modes` are the available preset modes - based on your configuration.
- `preset_mode` is the currently selected preset mode

**Comment by mbrevda** [comment] 2024-03-08 14:55
I see
But why are some entites missing the preset_modes altogether?

**Comment by paulius2k** [comment] 2024-03-10 11:14
@mbrevda have you _defined_ any of the `preset_modes` in the configuration of your "boys_room" thermostat?  Like `away:` or `home:`?  If you haven't, then they will not be available for you.

**Comment by mbrevda** [comment] 2024-03-10 11:15
Yes, I have - see yaml above

**Comment by paulius2k** [comment] 2024-03-10 11:30
Sorry, my bad for missing it.

Try fixing your temps in away preset:
    target_temp_low: ~~50~~    0
    target_temp_high: ~~0~~    50

**Comment by mbrevda** [comment] 2024-03-17 10:27
> This will fix your problem.

I don't think it did?

<img width="788" alt="Screenshot 2024-03-17 at 12 26 02 PM" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/293004/2f9dfcd8-845d-4b9a-a463-5b14dd7b3017">

**Comment by paulius2k** [comment] 2024-03-17 11:40
I tried it in my setup, and it works.  Then it could be some other parameter which is influencing this in your setup.:
<img src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/24705262/1b07ce8f-a041-49d2-aa32-7c7b70cc4fc9" width=70%>

P.S. sorry to ask, but you did remember to reload your yaml config after changes? :)

**Comment by mbrevda** [comment] 2024-03-17 12:25
>  did remember to reload your yaml config after changes

Yes, I did, and also reloaded home assistant when I didn't see the changes.

> I tried it in my setup, and it works

I'm sure. Where do I go from here?

**Comment by swingerman** [comment] 2024-03-17 14:07
I detected an issue that the supported features are detected when you change HVAC modes. supported_features sets if the thermostat supports preset mode or not.
It's bugg. Working on the fix.
Will be out in 1-2 days

**Comment by mbrevda** [comment] 2024-03-18 11:41
even in heat_cool mode? What would temperature be in that case?

**Comment by swingerman** [comment] 2024-03-18 11:52
Wait with this @mbrevda.
I am currently working on this. When in dual mode, this component can work in three different ways.
Just heater, just cooler or heat/cool mode. This requires `temperature`, `target_temp_low` and `target_temp_high` set.
But you should wait to set the temperature yourself as it cannot make sense for heating and cooling.
So the component should set it based on the current mode.
Logically if heater only mode, the temperature will be set to the `target_temp_low` value and in the cooling-only mode it will be set to `target_temp_high`

**Comment by swingerman** [comment] 2024-03-18 16:33
v0.9.5-beta.1 is out

**Comment by mbrevda** [comment] 2024-03-19 07:39
> v0.9.5-beta.1 is out

Thank you - it does not seem to have resolved the issue, though:

<img width="1032" alt="Screenshot 2024-03-19 at 9 30 38 AM" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/293004/bd512257-f0f0-4679-8738-3cd4af382c8e">

**Comment by swingerman** [comment] 2024-03-20 16:36
The only potential problem that I can see at this point is that the `target_temp_high` is higher than the `max_temp`

But I will take your config tomorrow and see. The `supported_features: 129` seems to indicate that preset modes are not supported.

**Comment by swingerman** [comment] 2024-03-21 13:11
Please check [v0.9.5-beta.3](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.5-beta.3)

I managed to reproduce and fix the issue. I also added a test to cover it.

[v0.9.5-beta.3](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.5-beta.3)

**Comment by mbrevda** [comment] 2024-03-27 06:44
I appreciate the efforts, but afraid the presets still aren't registering...

<img width="1034" alt="Screenshot 2024-03-27 at 8 41 55 AM" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/293004/ca8b3ad6-2ae8-4353-ba5a-f9127c940435">

**Comment by swingerman** [comment] 2024-04-10 15:24
Can you confirm that you use the same configuration that you used earlier?

**Comment by mbrevda** [comment] 2024-04-10 15:59
Exactly the same

**Comment by swingerman** [comment] 2024-04-10 16:09
Mirroring your confirmation, I can't reproduce the issue.
There may be some old state that was misconfigured and gets applied back.

Could you create a duplicate of `boys room` config with a different name and see?

**Comment by swingerman** [comment] 2024-05-24 12:17
Some saved state, probably saved with a buggy version, is being restored. Introducing a new name uses a new state and saved state.
Using the new name is the way to go forward.

**Closed by swingerman** 2024-05-24 12:17 UTC
Labels: bug

**Comment by mbrevda** [comment] 2024-05-24 12:43
Got it... finally!
I needed to stop ha (from the cli, via ssh) and remove the entity from `.storage/core.restore_state`. Then recreated the device and it's finally showing the preset states. Thanks for your help and patience in working though this!
