### ISSUE TITLE
Use the same switch for both heating and cooling

### ISSUE THREAD

**Issue by genioperso** [swingerman/ha-dual-smart-thermostat#225] opened 2024-06-25 09:00 UTC
In the case of an underfloor climate control system, the same solenoid valve controls both heating and cooling. In this case it is not possible to use dual smart thermostats in automatic mode because when the automation, depending on the room temperature, switches from winter to summer or vice versa, the following error message is received: 'cooler' entity cannot be equal to 'heater' entity. 'cooler' entity will be ignored; this prevents the automatic changeover from hot to cold and the switching must be made manually acting on the code.

**Comment by swingerman** [comment] 2024-06-27 06:58
this is a duplicate of a scheduled new feature #143

**Closed by swingerman** 2024-06-27 06:58 UTC
Labels: duplicate
